### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by AllenCC** [Ruinscraft/Panilla#2]
The Attack Damage attribute is not being cleared from items
https://i.gyazo.com/623db01eeb7eda7074f6861f099b9f2e.png
 
The only thing I have whitelisted in the config is Enchantments
https://pastebin.com/4CwguRrb

**Comment by dextonanderson** [comment]
I am not able to replicate this (I assume you are using 1.13 because of your config). Are you sure this isn't a ghost item? If it's not, could you provide me with the player .dat file located in /world/playerdata/player-uuid.dat 

Command I used to try to replicate this: `/give @p diamond_sword{AttributeModifiers:[{AttributeName:"generic.attackDamage", Name:"generic.attackDamage", Amount:2000, Operation:0, UUIDLeast:894654, UUIDMost:2872}]}`

**Comment by AllenCC** [comment]
Sorry it was actually a ghost item
