### ISSUE TITLE
Wiping NBT data from banners dropped in raids in 1.16.1

### ISSUE THREAD

**Issue by RWoof** [Ruinscraft/Panilla#58]
Getting this error:

[15:35:18 INFO]: [Panilla] NBT of an item entity was stripped because NBT tag HideFlags failed checks

Running panilla 1.5.4-fix

**Comment by dextonanderson** [comment]
Hi, this is not an error. This is indented behavior.

Basically, Panilla by default blocks the HideFlags NBT because it can be used "maliciously" on creative-mode servers.

You can:
- Add HideFlags to the NBT whitelist in the config
- Set the strictness to lenient in the config
- Add a world to the world whitelist in the config
- Ignore the message

**Comment by RWoof** [comment]
Thanks for the quick reply, the issue on the player end is the banner dropping as a white banner instead of the illager one. I have both creative and survival worlds using multiverse. If I whitelist the survival worlds it'll allow all exploits though right?

**Comment by dextonanderson** [comment]
It will put the world into "lenient" mode. Meaning only crash exploits will get blocked.

**Comment by RWoof** [comment]
An thank you, maybe that's safe in survival although we do have an anti cheat rule so I don't allow godly cheated items either. I have separate inventories between survival and creative so hopefully being more strict in creative alone will protect things enough.

**Comment by dextonanderson** [comment]
Yes, as long as you don't have people in creative-mode in your survival-mode world, they won't be able to edit the NBT on items.

**Comment by RWoof** [comment]
Thanks for your help!
